### ISSUE TITLE
Enable Arabic segmentation with CoreNLP

### ISSUE THREAD

**Issue by Jibun** [dkpro/dkpro-core#1216]
Stanford CoreNLP already provides an option to run an Arabic segmenter based on a pre-trained model.
This feature, however, is not enabled on the CoreNLP wrapper for DKPro (seems to be almost finished).

- [x] Add `ar` segmenter model to `build.xml` to package it for use with the CoreNlpSegmenter
- [x] Add `PARAM_MODEL_LOCATION` to CoreNlpSegmenter

**Comment by Jibun** [comment]
Our proposal (UPF-TALN) is doing as follows:
- Adding the _models-arabic_ dependency of _edu.stanford.nlp.stanford-corenlp_ in the pom
- Setting a default location for arabic model contained in the dependency: _edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb+bn+arztrain.ser.gz_
- Passing _segment.model_ parameter to CoreNLP with the default location of the Arabic model
- Adding an optional parameter to specify a local model path. In case of being specified this local model will be loaded insted of the default one.

**Comment by reckart** [comment]
Models should be added via the usual mechanism: https://dkpro.github.io/dkpro-core/releases/1.9.1/docs/developer-guide.html#_packaging_resources

The CoreNLP segmenter (old and new) currently assume that the segmenter does not need a model. The supported language/segmenter map is basically hard-coded in the old one (`StanfordSegmenter`). The new one (`CoreNlpSegmenter`) already uses a resource provider, but tells the provider that actually no model is required.

It should be pretty simple to add a new optional parameter with the model location. If set, it could override the default location which is `NOT_REQUIRED`. If the user manually adds the required dependency to the POM, this should allow to load the model. 

It would probably also be sensible to add the `PARAM_MODEL_ARTIFACT_URI` parameter to allow loading the model from an artifact at runtime (mind that artifacts are by default only resolved in the UKP model repo at the moment - should probably be changed as well to include Maven Central).

I think with these changes, using the CoreNLP Segmenter with the arabic model should work. But auto-loading the model simply by specifying `ar` as the document language would require extra changes.

**Comment by Jibun** [comment]
We have been testing and it looks like if the `modelLocation` is provided, the default location can be kept as `NOT_REQUIRED`, for the resource provider uses the `modelLocation` information. Later on the segmenter needs a property `segment.model` that is not automatically set by the resource provider. We set it manually with the information returned by the provider.

We have also managed to load the Stanford CoreNLP default Arabic model if no model is provided and language is `ar` by packaging it to fit your dependencies structure. We could provide you with the jar and the pom so you could deploy it into your DKPro repo, or you could package it yourself. This way the Arabic segmenter will work in all cases, otherwise it will crash if no model is provided.

What do you think?

**Comment by reckart** [comment]
@Jibun I'm not sure I have understood what is happening where. When you say that `segment.model` is needed "later", when/where does "later" mean? And when you say you set it "manually", when/where does that happen? Are changes to the code necessary or do you set everything you need from the outside?

For the model, could you provide a PR  for `dkpro-core-corenlp-gpl/src/scripts/build.xml` with a new Ant target which packages the "ar" model? I can then run that target to upload the packaged model to our repo and others can also run it if they want/need to package themselves. It also facilitates upgrades to newer versions of CoreNLP if we can automatically package the models and do not have to do that manually.

Btw. we now have a feature in DKPro Core that allows explicitly specifying the Maven coordinates of a JAR with a model: #1212.

**Comment by Jibun** [comment]
@reckart `segment.model` is needed as a property when initializing the `TokenizerAnnotator`. I set it in the `produceResource` method within `ModelProviderBase<TokenizerAnnotator>` inside `CoreNlpSegmenter` class.

**Comment by reckart** [comment]
@Jibun ok, so we need definitely need to add a `PARAM_MODEL_LOCATION` because we start working with models now. We also need a packaged version of the `ar` model that is compatible with the DKPro Core standards. I have added these two items to a todo list in the first issue comment.

I believe we don't have an optimal solution yet for handling the case that some segmenters require a model and others not. The first problem is, that the DKPro Core model provider can either work in a mode where no model is required (`NOT_REQUIRED`) or where a model is used (using a classpath pattern for the default model location which takes into account language and variant).

We could get around this problem by using `NOT_REQUIRED` as the default value for `PARAM_MODEL_LOCATION` and require the user to manually enter a model location for use with arabic. But it would be much better if the user wouldn't have to interfere. I.e. we should automatically load a model if one is required and not try loading a model if none is required. But how does the model provider / CoreNlpSegmenter know which languages require a model and which do not.

If you look at the model provider, it usually does not load the model directly, but instead it loads a properties file which includes a pointer to the actual model file along with some additional metadata.

My idea would be to create such properties files for all the rule-based languages supported by CoreNlpSegmenter and inside them set the `location` to `-=* NOT REQUIRED *=-`. As part of packaging the `ar` model, we also create such a properties file, but it will actually contain a proper location pointing to the modle file. In that way, the model provider could automatically detect if a model is required or not. It might require adjustments to the model provider code though. I think right now it is not supported to defer knowing if a model location exists until after the properties file has been loaded.

WDYT?

**Comment by Jibun** [comment]
@reckart Ok, I understand that these properties files are automatically generated by the Ant script that packages the models. So in these cases, where there are no models, the files should be created by hand.

```
#
#Tue, 08 May 2018 16:58:45 +0200

generated=2018/05/08 16\:58
version=20170609.1
language=ar
variant=stanford
tool=tokenizer
location=classpath\:/de/tudarmstadt/ukp/dkpro/core/corenlp/lib/tokenizer-ar-stanford.ser.gz
```
Here is a sample file for the Arabic model we packaged.

Should all the parameters be specified? I assume `variant` could be for instance `none`, but what about `generated`, and `version`?

**Comment by reckart** [comment]
Technically, the only property that we probably have to specify is `location=-=* NOT REQUIRED *=-` (probably with some escaping)... then place the properties files into the same package as the file generated by the Ant script, but directly in the `src/main/resources` folder of the `corenlp` module. Then change the default location in the `CoreNlpSegmenter` into a pattern which tries to load the properties from that location (cf. CoreNlpPosTagger).

**Comment by reckart** [comment]
@Jibun I think we are done here with #1255 having been merged, right?

**Comment by Jibun** [comment]
Done and merged
