### ISSUE TITLE
Integrate MyStem (Russian stemmer)

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#1308]
Integration of a Russian stemmer https://tech.yandex.ru/mystem/
Closed-source, distributed as pre-compiled fat binaries that seem to include the model.

Non-profit/research use is permitted, commercial usage has constrained. Website is Russian only~

**Comment by Horsmann** [comment]
@reckart The stemmer is essentially completed but I will definitely not replace tabs with whitespaces. Can this checkstyle stuff be turned off?

**Comment by reckart** [comment]
The style guidelines we have since ages define spaces instead of tabs. Checkstyle just enforces that for a better experience. Tabs have the problem that different viewers use different tab widths (2, 4, 8, whatever) which makes the code look very differently in different viewers. Spaces do not have this problem. Please install the [DKPro Core Style file for Eclipse](https://dkpro.github.io/contributing/) or correspond whatever IDE you are using correspondingly.

**Comment by reckart** [comment]
Mind that the style file does not take XML files into account - but they should also be formatted with spaces and use 2 space characters for indentation.
