### ISSUE TITLE
PARAM_PATTERNS not a constant in dkpro.core.api.parameter-asl

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#649]
The PARAM_PATTERNS parameter that is available for all(?) collection reader does not map to a constant value in the parameter-asl.

This is how it looks at the moment
 public static final String PARAM_PATTERNS = "patterns";
    @ConfigurationParameter(name = PARAM_PATTERNS, mandatory = false)
    private String[] patterns;

Is there a reason for this or was it just overseen when the parameters project was added?

**Comment by reckart** [comment]
It could be moved to parameter-asl. It was probably not done, because most (all?) readers that support the parameter inherit from ResourceCollectionReaderBase anyway. Mind that FileSetCollectionReaderBase (the other component offering the parameter) is deprecated.

Feel free to create a constant in parameters-asl for the parameter.

**Comment by Horsmann** [comment]
I added the patterns parameter
