### ISSUE TITLE
graf-asl on Maven?

### ISSUE THREAD

**Issue by annefried** [dkpro/dkpro-core#686]
Hi,
I can't find the package de.tudarmstadt.ukp.dkpro.core.io.graf-asl on Maven Central, and the GrafWriter class does not seem to be included in another artifact either. Is that intended?
Thanks a lot!

**Comment by reckart** [comment]
Yes, the graf module is not part of the DKPro Core releases yet.

It is not finished yet because the round-trip UIMA->GrAF->UIMA currently fails (https://github.com/dkpro/dkpro-core/issues/110).

Also, I think the dependencies of the GrAF module are only available from an ANC repository, but not from Maven Central. I didn't check right now, but there might even be SNAPSHOT dependencies.

@ksuderman FYI

**Comment by reckart** [comment]
The GrAF UIMA library from ANC is not compatible with UIMA v3. So for the moment, we keep the module as an "experimental" one that is in the code repository but not in the releases. As it looks like now, latest with the switch to UIMA v3 in the future it will be dropped.
