### ISSUE TITLE
Check for input type annotations

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#837]
As discussed in #575 and https://github.com/dkpro/dkpro-core/commit/eaabf7009f7882d087acd4b7164ed5cc37e0ff54, input types may be necessary for an annotator class in order to work. If they do not exist, the result is currently unpredictable and may yield a `NullPointerException?  which makes it difficult to trace back to the cause.

I have several ideas for potential solutions:

1. mark input types as optional, recommended, or required (or assume they always are required)
2. assert that at least one annotation of each of the specified input types exists upon initialization
3. issue a warning or throw a meaningful exception respectively if an optional or required input type annotation does not exist.

These ideas do not necessarily depend on each other. However, this might actually need to be implemented in UIMA Fit (class `JCasAnnotator_ImplBase`?).

**Comment by reckart** [comment]
I am pretty sure we already have an issue for this (which I don't find right now, maybe was only discussed on the mailing list) and also some related issues (#135, #443). The problem is that the input/output type declarations are not mandatory and may not always be completely reliable, e.g.:

* the required types may depend on the setting of parameters (e.g. PARAM_READ_POS in StanfordParser)
* the required types may depend on the model being used (e.g. MaltParser)

I think we should have some easy-to-use convenience methods in some utility class and used that to kind of centralize the checking for the presence of types depending on the concrete circumstances. But doing it based on the input/output type declarations is not flexible enough.

**Comment by carschno** [comment]
I suppose you are right. I'll hence open a new issue about the specific issue mentioned in https://github.com/dkpro/dkpro-core/commit/eaabf7009f7882d087acd4b7164ed5cc37e0ff54.
