### ISSUE TITLE
BlikiWikipediaReaderTests sometimes fail

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#891]
When I run the BlikiWikipediaReader tests locally, it fails occasionally. This is also true for the other test in the testcase:

  - wikipediaReaderTestPlainText() failed 11 times in 100 runs.
  - wikipediaReaderTestMarkup() failed 10 times in 100 runs
  - wikipediaReaderUnknownPage() failed 13 times in 100 runs.

I guess that this due to the Wikipedia API. How could we confirm this
and deal with it?

**Comment by betoboullosa** [comment]
I've seen this happen sometimes when preparing the 1.8.0 release. It's probably because of the wikipedia Web service being inaccessible for some reason during the test. Manually re-running the test (sometimes more than once) after the error usually works. One possibility would be automatically running the test again if an error is received (with a threshold in the number of tries). Or testing the error code to see if it's a connection problem and then bypassing the test.

**Comment by carschno** [comment]
I agree that this is likely a server/API problem, but it does not report a failure. Instead, the result set is just empty (which is why the test fails). However, a unit test that is allowed to fail seems not very useful, so unless we find a better solution I agree with @reckart and we should ignore it.

**Comment by logological** [comment]
Relevant discussion on Stack Overflow: [How to safely test code requiring an external web API](https://stackoverflow.com/questions/34655819/how-to-safely-test-code-requiring-an-external-web-api)
