### ISSUE TITLE
Publish solrServer in SolrWriter_impl

### ISSUE THREAD

**Issue by betoboullosa** [dkpro/dkpro-core#981]
solrServer property is private  in SolrWriter_impl, it should be accessible to anyone trying to implement its own writer.

**Comment by carschno** [comment]
You mean `solrClient`, right? I cannot think of a scenario in which makes sense to initialize an own `solrClient` instance in a sub-class. All the necessary parameters (queue size and thread count) can be passed through the DKPro parameters.
However, a getter method might be useful, even though most implementations will only need to override `generateSolrDocument()` in order to produce `SolrInputDocument`s which will then be handled by the super-class.

**Comment by betoboullosa** [comment]
Yes, I meant solrClient. I needed to access it in the implementation of generateSolrDocument() in a writer that I'm creating.

**Comment by reckart** [comment]
We needed to generate multiple solr documents from a single CAS, so generateSolrDocument() didn't work for us.

**Comment by carschno** [comment]
Another approach could have been to change `generateSolrDocument()` so that it returns a collection of SolrInputDocuments; which may clearly contain only one document.

**Comment by betoboullosa** [comment]
Actually in the way it is now, I had to create a dummy generateSolrDocument method in my writer, since it's an obligatory method to implement.

Are you telling to change the return type in the base class method? Won't that interfere with other writers who might already use it as it is now?
