### ISSUE TITLE
Add Stockholm University Swedish POS Tagger

### ISSUE THREAD

**Issue by munterkalmsteiner** [dkpro/dkpro-core#991]
Swedish POS Tagger that uses the Stockholm-Umeå Corpus and tag set (http://www.ling.su.se/english/nlp/tools/stagger). Could then be used with the Maltparser and model which uses the same corpus and tag set.
Mostly implemented and currently testing.

**Comment by reckart** [comment]
What would be the name/artifactId of the new module? I would suggest `dkpro-core-stockholm`?

Please mind that for new components, we now use the package name `org.dkpro.core.XXX`, and the Maven GroupId in new modules should be `org.dkpro.core`.

**Comment by mikmakmuk** [comment]
I'd rather use the upstream name "stagger" rather than "stockholm".
Then, I've followed the naming scheme from stanford NLP, i.e.:
- artifactId: de.tudarmstadt.ukp.dkpro.core.stagger-gpl
- folder name: dkpro-core-stagger-gpl
- package name: de.tudarmstadt.ukp.dkpro.core.stagger

I can change that to:
- artifactId: org.dkpro.core.stagger
- groupId: org.dkpro.core
- folder name: dkpro-core-stagger
- package name: org.dkpro.core.stagger

Would that work?

**Comment by reckart** [comment]
That's fine.

**Comment by reckart** [comment]
@munterkalmsteiner I wonder if you somehow forgot about this? ;)
